### ISSUE TITLE
Line counter

### ISSUE THREAD

**Issue by davidc25tlumby** [davidc25tlumby/EECS2311-Group-11#7]
Current the scenario is edited using "currentLine" which is an integer counter. Since each line is actually represented by an unique ID, using currentLine would not work once the file is edited. Instead, editing should be done using the LinkedList id to determine what ID should be altered given the currentLine. e.g. id.get(currentLine) would be the ID to edit.

**Comment by CuHuyHoangMinh** [comment]
fix it
